import { useEffect, useState } from 'react'
import { Link, useNavigate, useSearchParams, useParams } from 'react-router-dom'
import { apiFetch } from '../api/client'
import type { LearningResourcesPayload } from '../types'
import '../styles/App.css'

export function ResourcesPage() {
  const { code } = useParams<{ code?: string }>()
  const [searchParams] = useSearchParams()
  const navigate = useNavigate()

  const [data, setData] = useState<LearningResourcesPayload | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [activeTab, setActiveTab] = useState<'all' | 'videos' | 'notes' | 'docs' | 'articles' | 'practice' | 'playlists'>('videos')
  const [selectedLanguage, setSelectedLanguage] = useState<'All' | 'English' | 'Tamil'>('All')
  const [sortBy, setSortBy] = useState('Recommended')

  const fetchResources = async () => {
    setLoading(true)
    setError(null)
    try {
      const targetCode = code || 'java'
      const requestedTopic = searchParams.get('topic') || ''
      const langParam = selectedLanguage !== 'All' ? `&language=${selectedLanguage}` : ''
      const res = await apiFetch<LearningResourcesPayload>(
        `/courses/${targetCode}/resources?topic=${encodeURIComponent(requestedTopic)}${langParam}`
      )
      setData(res)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unable to load resources')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchResources()

    const handleCourseSwitch = () => {
      fetchResources()
    }
    window.addEventListener('course-switched', handleCourseSwitch)
    return () => window.removeEventListener('course-switched', handleCourseSwitch)
  }, [code, searchParams, selectedLanguage])

  const downloadNotesPDF = () => {
    if (!data) return
    const content = `${data.course.title} - ${data.topic} Quick Notes\n\n` +
      data.quickNotes.bullets.map((b, i) => `${i + 1}. ${b}`).join('\n\n') +
      `\n\nGenerated by Adaptive Learner AI.`
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${data.course.code}_${data.topic.replace(/\s+/g, '_')}_notes.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  if (loading) {
    return (
      <div className="resources-loading-wrap">
        <div className="dash-loader">
          <div className="dash-spinner" />
          <p>Curating personalized learning resources...</p>
        </div>
      </div>
    )
  }

  if (error || !data) {
    return (
      <div className="resources-error-wrap">
        <div className="dash-error-card">
          <span className="dash-error-icon">⚠️</span>
          <h2>Unable to load learning resources</h2>
          <p>{error || 'No resources available for this topic.'}</p>
          <button onClick={() => fetchResources()}>Retry</button>
        </div>
      </div>
    )
  }

  const { course, topic, progress, englishResources, tamilResources, quickNotes, additionalDocs, tutorTip } = data

  const showEnglish = selectedLanguage === 'All' || selectedLanguage === 'English'
  const showTamil = selectedLanguage === 'All' || selectedLanguage === 'Tamil'

  return (
    <div className="resources-page-container">
      {/* 1. Breadcrumbs matching Screenshot 2 */}
      <nav className="resources-breadcrumb" aria-label="Breadcrumb">
        <Link to="/courses" className="breadcrumb-link">My Courses</Link>
        <span className="breadcrumb-sep">&gt;</span>
        <Link to={`/courses/${course.code}/journey`} className="breadcrumb-link">{course.title}</Link>
        <span className="breadcrumb-sep">&gt;</span>
        <span className="breadcrumb-topic">{topic}</span>
        <span className="breadcrumb-sep">&gt;</span>
        <span className="breadcrumb-active">Learning Resources</span>
      </nav>

      {/* 2. Header Banner matching Screenshot 2 */}
      <section className="resources-header-banner">
        <div className="banner-left-content">
          <div className="topic-icon-badge" aria-hidden="true">
            <span className="badge-letter">
              {course.title.charAt(0).toUpperCase()}
            </span>
          </div>
          <div>
            <h1 className="topic-title">{topic}</h1>
            <p className="topic-category">Learning Resources</p>
            <p className="topic-description">
              Explore videos, notes, documentation and practice materials to master {topic}.
            </p>
          </div>
        </div>

        {/* Right Circular Progress Card matching Screenshot 2 */}
        <div className="topic-progress-card">
          <div className="donut-circle-wrap">
            <svg className="donut-svg" viewBox="0 0 72 72">
              <circle className="donut-bg" cx="36" cy="36" r="28" />
              <circle
                className="donut-fill"
                cx="36"
                cy="36"
                r="28"
                strokeDasharray={`${2 * Math.PI * 28}`}
                strokeDashoffset={`${2 * Math.PI * 28 * (1 - (progress || 42) / 100)}`}
              />
            </svg>
            <span className="donut-pct-text">{progress || 42}%</span>
          </div>

          <div className="progress-info-wrap">
            <h3 className="progress-card-heading">Your Progress in {topic}</h3>
            <p className="progress-card-sub">
              Keep learning! Explore resources and practice more questions.
            </p>
            <button
              onClick={() => navigate(`/practice?topic=${encodeURIComponent(topic)}`)}
              className="go-to-practice-btn"
              type="button"
            >
              Go to Practice →
            </button>
          </div>
        </div>
      </section>

      {/* 3. Filter Navigation & Dropdowns Bar matching Screenshot 2 */}
      <div className="resources-filter-bar">
        {/* Left Tabs */}
        <div className="filter-tabs-list" role="tablist">
          {[
            { id: 'all', label: 'All' },
            { id: 'videos', label: 'Videos', icon: '▶' },
            { id: 'notes', label: 'Notes', icon: '📝' },
            { id: 'docs', label: 'Docs', icon: '📄' },
            { id: 'articles', label: 'Articles', icon: '📰' },
            { id: 'practice', label: 'Practice', icon: '⚡' },
            { id: 'playlists', label: 'Playlists', icon: '📑' },
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id as any)}
              className={`tab-btn ${activeTab === tab.id ? 'is-active' : ''}`}
              type="button"
            >
              {tab.icon && <span className="tab-icon">{tab.icon}</span>}
              {tab.label}
            </button>
          ))}
        </div>

        {/* Right Dropdowns: Language & Sort By */}
        <div className="filter-dropdowns-wrap">
          <div className="dropdown-field">
            <span className="dropdown-label">Language:</span>
            <select
              value={selectedLanguage}
              onChange={(e) => setSelectedLanguage(e.target.value as any)}
              className="dropdown-select"
            >
              <option value="All">All</option>
              <option value="English">English</option>
              <option value="Tamil">Tamil (தமிழ்)</option>
            </select>
          </div>

          <div className="dropdown-field">
            <span className="dropdown-label">Sort by:</span>
            <select
              value={sortBy}
              onChange={(e) => setSortBy(e.target.value)}
              className="dropdown-select"
            >
              <option value="Recommended">Recommended</option>
              <option value="Most Viewed">Most Viewed</option>
              <option value="Highest Rated">Highest Rated</option>
              <option value="Newest">Newest</option>
            </select>
          </div>
        </div>
      </div>

      {/* 4. Main 2-Column Content Grid matching Screenshot 2 */}
      <div className="resources-content-grid">
        {/* Left Column: English & Tamil Video Cards */}
        <div className="resources-main-column">
          {/* Section 1: English Resources */}
          {showEnglish && (
            <section className="resource-section">
              <div className="section-header">
                <div>
                  <div className="flex items-center gap-2">
                    <span className="section-header-icon" aria-hidden="true">🌐</span>
                    <h2 className="section-title">English Resources</h2>
                  </div>
                  <p className="section-subtitle">High quality learning videos in English</p>
                </div>
                <button
                  onClick={() => alert("Showing all available curated videos for " + topic)}
                  className="section-view-all"
                  type="button"
                >
                  View All →
                </button>
              </div>

              <div className="videos-card-grid">
                {englishResources.map((vid, idx) => (
                  <article key={idx} className="video-card">
                    {/* Thumbnail Box */}
                    <div className="video-thumb-box">
                      <div className="video-mockup-bg">
                        <span className="mockup-topic-tag">{course.title}</span>
                        <h4 className="mockup-heading">{topic}</h4>
                        <span className="mockup-subtag">for Beginners</span>
                      </div>
                      <span className="video-duration-badge">{vid.duration}</span>
                    </div>

                    {/* Meta info */}
                    <div className="video-meta-body">
                      <div className="video-title-row">
                        <h3 className="video-card-title">
                          <a href={vid.url} target="_blank" rel="noreferrer">
                            {vid.title}
                          </a>
                        </h3>
                        <button className="video-options-btn" type="button" title="Options">⋮</button>
                      </div>

                      <div className="video-channel-row">
                        <div className="channel-avatar-circle">
                          {vid.channel.charAt(0)}
                        </div>
                        <span className="channel-name">{vid.channel}</span>
                      </div>

                      <p className="video-views-row">{vid.views} · {vid.age}</p>
                    </div>
                  </article>
                ))}
              </div>
            </section>
          )}

          {/* Section 2: Tamil Resources */}
          {showTamil && (
            <section className="resource-section mt-8">
              <div className="section-header">
                <div>
                  <div className="flex items-center gap-2">
                    <span className="section-header-icon" aria-hidden="true">🇮🇳</span>
                    <h2 className="section-title">Tamil Resources</h2>
                  </div>
                  <p className="section-subtitle">Learn in your native language (தமிழ்)</p>
                </div>
                <button
                  onClick={() => alert("Showing all available curated Tamil videos for " + topic)}
                  className="section-view-all"
                  type="button"
                >
                  View All →
                </button>
              </div>

              <div className="videos-card-grid">
                {tamilResources.map((vid, idx) => (
                  <article key={idx} className="video-card">
                    {/* Thumbnail Box */}
                    <div className="video-thumb-box">
                      <div className="video-mockup-bg tamil-mockup">
                        <span className="mockup-topic-tag">{course.title} ல்</span>
                        <h4 className="mockup-heading">{topic}</h4>
                        <span className="mockup-subtag">விளக்கம்</span>
                      </div>
                      <span className="video-duration-badge">{vid.duration}</span>
                    </div>

                    {/* Meta info */}
                    <div className="video-meta-body">
                      <div className="video-title-row">
                        <h3 className="video-card-title">
                          <a href={vid.url} target="_blank" rel="noreferrer">
                            {vid.title}
                          </a>
                        </h3>
                        <button className="video-options-btn" type="button" title="Options">⋮</button>
                      </div>

                      <div className="video-channel-row">
                        <div className="channel-avatar-circle tamil-avatar">
                          {vid.channel.charAt(0)}
                        </div>
                        <span className="channel-name">{vid.channel}</span>
                      </div>

                      <p className="video-views-row">{vid.views} · {vid.age}</p>
                    </div>
                  </article>
                ))}
              </div>
            </section>
          )}
        </div>

        {/* Right Column: Quick Notes, Additional Resources, Tip from AI Tutor */}
        <aside className="resources-side-column">
          {/* Card 1: Quick Notes matching Screenshot 2 */}
          <div className="side-card quick-notes-card">
            <div className="notes-header-row">
              <div className="flex items-center gap-2">
                <span className="notes-icon" aria-hidden="true">📖</span>
                <h3 className="side-card-title">Quick Notes</h3>
              </div>
              <button
                onClick={downloadNotesPDF}
                className="download-pdf-btn"
                type="button"
              >
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                  <polyline points="7 10 12 15 17 10"/>
                  <line x1="12" y1="15" x2="12" y2="3"/>
                </svg>
                Download PDF
              </button>
            </div>

            <ul className="notes-bullets-list">
              {quickNotes.bullets.map((bullet, idx) => (
                <li key={idx} className="note-bullet-item">
                  <span className="bullet-dot">•</span>
                  <span>{bullet}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Card 2: Additional Resources matching Screenshot 2 */}
          <div className="side-card additional-resources-card">
            <div className="flex items-center gap-2 mb-4">
              <span className="links-icon" aria-hidden="true">🔗</span>
              <h3 className="side-card-title">Additional Resources</h3>
            </div>

            <div className="additional-links-list">
              {additionalDocs.map((doc, idx) => (
                <a
                  key={idx}
                  href={doc.url}
                  target="_blank"
                  rel="noreferrer"
                  className="additional-link-item"
                >
                  <div className="link-logo-box">
                    {doc.provider === 'gfg' && <span className="provider-code green">GFG</span>}
                    {doc.provider === 'w3' && <span className="provider-code teal">W3</span>}
                    {doc.provider === 'oracle' && <span className="provider-code red">DOC</span>}
                    {doc.provider === 'python' && <span className="provider-code blue">PY</span>}
                    {doc.provider === 'leetcode' && <span className="provider-code amber">LC</span>}
                    {doc.provider === 'indiabix' && <span className="provider-code indigo">BIX</span>}
                    {!['gfg', 'w3', 'oracle', 'python', 'leetcode', 'indiabix'].includes(doc.provider) && (
                      <span className="provider-code purple">REF</span>
                    )}
                  </div>
                  <div className="link-text-wrap">
                    <p className="link-doc-name">{doc.name}</p>
                    <p className="link-doc-action">{doc.type} →</p>
                  </div>
                </a>
              ))}
            </div>
          </div>

          {/* Card 3: Tip from AI Tutor matching Screenshot 2 */}
          <div className="side-card tutor-tip-card">
            <div className="flex items-center gap-2 mb-2">
              <span className="tip-bulb-icon" aria-hidden="true">💡</span>
              <h3 className="tip-title">Tip from AI Tutor</h3>
            </div>
            <p className="tip-text">
              {tutorTip || "Try watching one video and solve at least 5 practice questions to strengthen your understanding!"}
            </p>
          </div>
        </aside>
      </div>
    </div>
  )
}
